### ISSUE TITLE
vmmap command not working

### ISSUE THREAD

**Issue by matbun** [Byzero512/vmmap-win-cmd#1]
Hi! I have downloaded the full Release directory to c:\Program Files\Vmmap and added  c:\Program Files\Vmmap to the Path env variable.
In the command prompt, when I run  vmmap -pid <random_pid_from_taskmgr> the process keeps hanging for a while and then exits.
I would like to use it for wibe (https://github.com/Byzero512/peda-windows/tree/master/mingw-gdb/wibe), but I got the following python error when using gdb-wibe:
```
'vmmap64.exe' is not recognized as an internal or external command,
operable program or batch file.
Python Exception <class 'subprocess.CalledProcessError'> Command 'vmmap64.exe -pid 18104 -all' returned non-zero exit status 1:
```
Where can I get vmmap64.exe?

**Comment by Byzero512** [comment]
compile the source code with x64 as the target, then rename the binary vmmap.exe to vmmap64.exe.
